{% set name = "ff" %}
{% set version = "2.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/hep-packaging-coordination/ff/archive/v{{ version }}.tar.gz
  sha256: 0f72c620bca93f62deed3194b56b34e66071c512cb8bc63be7aeedc35be7cbfc

build:
  number: 1

outputs:
  - name: {{ name }}-static

    build:
      skip: true  # [win]
      script:
        # FIXME: Patch out custom paths
        # Note: Need the space at the end of '$PREFIX/share/ff/ ' so that
        #
        # fullname = path(1:index(path,' ')-1)//names
        #
        # in src/ff/ffinit.f can have a space to split on.
        # This is a bug and should get fixed by using better logic for fullname.
        - sed -i "s|/user/gj/lib/|$PREFIX/share/ff/ |g" src/ff/ffinit.f
        - sed -i "s|/usr/local/ff/|$PREFIX/share/ff/ |g" src/ff/ffinit.f

        - cd src/ff
        - make install FC=$FC FFLAGS="$FFLAGS -std=legacy -ffixed-line-length-none" DEST=$PREFIX/lib --jobs="${CPU_COUNT}"
        - mkdir -p $PREFIX/include/ff
        - mv *.h $PREFIX/include/ff
        - mkdir -p $PREFIX/share/ff
        - mv *.dat $PREFIX/share/ff/

    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('fortran') }}
        - make
        - libtool
        - sed

    test:
      source_files:
        - src/ff/npointes.f
      requires:
        - {{ compiler('fortran') }}
      commands:
        - test -f $PREFIX/lib/libff.a
        - test -f $PREFIX/include/ff/aa.h
        - test -f $PREFIX/include/ff/ff.h
        - test -f $PREFIX/include/ff/ffs.h
        - test -f $PREFIX/share/ff/fferr.dat
        - test -f $PREFIX/share/ff/ffperm5.dat
        - test -f $PREFIX/share/ff/ffwarn.dat

        - $FC ./src/ff/npointes.f -o npointes $FFLAGS -I$PREFIX/include/ff $LDFLAGS -lff
        - ./npointes

about:
  home: https://github.com/hep-packaging-coordination/ff
  summary: 'FF: a package to evaluate one-loop integrals'
  description: |
    FF is a package to evaluate one-loop integrals written by G. J.
    van Oldenborgh, NIKHEF-H, Amsterdam. For the the algorithms used see
    preprint NIKHEF-H 89/17, 'New Algorithms for One-loop Integrals', by
    G.J. van Oldenborgh and J.A.M. Vermaseren, published in Zeitschrift
    fuer Physik C46(1990)425.
    [DOI: 10.1007/BF01621031](https://doi.org/10.1007/BF01621031)
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/hep-packaging-coordination/ff

extra:
  feedstock-name: ff
  recipe-maintainers:
    - matthewfeickert
